# Generated by Django 5.0.4 on 2024-04-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billedproduct',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='billedProducts',
        ),
        migrations.AddField(
            model_name='bill',
            name='billedProducts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.billedproduct'),
            preserve_default=False,
        ),
    ]
