# Generated by Django 5.0.4 on 2024-04-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_billedproduct_bill_remove_bill_billedproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='billedProducts',
        ),
        migrations.AddField(
            model_name='billedproduct',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billedProduct', to='billing.bill'),
            preserve_default=False,
        ),
    ]
