# Generated by Django 5.0.4 on 2024-04-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_billedproducts_billedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
