# Generated by Django 5.0.4 on 2024-04-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='billedproduct',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
