# Generated by Django 5.0.4 on 2024-04-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_bill_billedproducts_billedproduct_bill'),
        ('billing', '0004_alter_bill_total_alter_billedproduct_price'),
    ]

    operations = [
    ]
