# Generated by Django 5.0.4 on 2024-04-08 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_bill_total_alter_billedproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billedproduct',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='billing.bill'),
        ),
        migrations.AlterField(
            model_name='billedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='billing.product'),
        ),
    ]
